"""Generate Kotlin wire data classes from the canonical exported JSON schemas."""
import json
import re
from pathlib import Path

root = Path(__file__).resolve().parents[1]
models = {}
for path in sorted((root / "contracts/schemas").glob("*.json")):
    schema = json.loads(path.read_text(encoding="utf-8"))
    models.update(schema.get("$defs", {}))
    models[path.stem] = schema

def camel(name):
    return re.sub(r"_([a-z0-9])", lambda m: m.group(1).upper(), name)

def kt(schema):
    if "$ref" in schema:
        return schema["$ref"].rsplit("/", 1)[1]
    if "anyOf" in schema:
        choices = [s for s in schema["anyOf"] if s.get("type") != "null"]
        return (kt(choices[0]) if len(choices) == 1 else "JsonElement") + ("?" if len(choices) != len(schema["anyOf"]) else "")
    return {"string": "String", "integer": "Long", "number": "Double", "boolean": "Boolean",
            "array": lambda: "List<" + kt(schema["items"]) + ">",
            "object": lambda: "Map<String, " + kt(schema.get("additionalProperties", {})) + ">"}.get(schema.get("type"), "JsonElement") if schema.get("type") not in ["array", "object"] else ("List<" + kt(schema["items"]) + ">" if schema["type"] == "array" else "Map<String, " + kt(schema.get("additionalProperties", {}) if isinstance(schema.get("additionalProperties", {}), dict) else {}) + ">")

lines = ["// Generated by scripts/generate_kotlin_contracts.py. Do not edit by hand.", "package io.praxis.sdk.contracts", "", "import kotlinx.serialization.SerialName", "import kotlinx.serialization.Serializable", "import kotlinx.serialization.json.JsonElement", ""]
for name, schema in sorted(models.items()):
    if "enum" in schema and schema.get("type") == "string":
        lines += ["@Serializable", f"enum class {name} {{"]
        lines += [f'    @SerialName({json.dumps(v)}) {v.upper()},' for v in schema["enum"]]
        lines += ["}", ""]
        continue
    if schema.get("type") != "object" or "properties" not in schema:
        continue
    lines += ["@Serializable", f"data class {name}("]
    required = schema.get("required", [])
    for field, spec in schema["properties"].items():
        kind = kt(spec)
        default = ""
        if field not in required:
            if "default" in spec and spec["default"] is not None:
                value = spec["default"]
                if "$ref" in spec and isinstance(value, str):
                    default = " = " + kind + "." + value.upper()
                elif isinstance(value, (str, bool, int, float)):
                    default = " = " + (str(float(value)) if kind == "Double" else json.dumps(value))
                else:
                    kind += "?" if not kind.endswith("?") else ""
                    default = " = null"
            else:
                kind += "?" if not kind.endswith("?") else ""
                default = " = null"
        lines.append(f'    @SerialName("{field}") val {camel(field)}: {kind}{default},')
    lines += [")", ""]
out = root / "android-sdk/praxis/src/main/kotlin/io/praxis/sdk/contracts/Contracts.kt"
out.parent.mkdir(parents=True, exist_ok=True)
out.write_text("\n".join(lines), encoding="utf-8")
print("Generated", len(models), "canonical Kotlin types")
